packaging_format = 2

id = "chatgpt-web"
name = "chatGPT-web"
description.en = "ChatGPT web interface using the OpenAI API"
description.fr = "Interface Web ChatGPT utilisant l'API OpenAI"

version = "2023.09.01~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://niek.github.io/chatgpt-web/"
demo = "https://niek.github.io/chatgpt-web/"
code = "https://github.com/Niek/chatgpt-web"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/Niek/chatgpt-web/archive/4fa583a35cb4deff552e204b8f196dbdb019a611.tar.gz"
        sha256 = "8b1ea41d1140afdb41dfbdc46b2bc7932b26ba0a1d6152f6fb17520e9f7e33e9"
        autoupdate.upstream = "https://github.com/Niek/chatgpt-web"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5174
