packaging_format = 2

id = "chatgpt-web"
name = "chatGPT-web"
description.en = "ChatGPT web interface using the OpenAI API"
description.fr = "Interface Web ChatGPT utilisant l'API OpenAI"

version = "2023.05.29~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://niek.github.io/chatgpt-web/"
demo = "https://niek.github.io/chatgpt-web/"
code = "https://github.com/Niek/chatgpt-web"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/Niek/chatgpt-web/archive/3e08e8c16d6eba73265ec907b22b9f9b9f4efee4.tar.gz"
        sha256 = "acb03dbfccea31d72e39ac801cb92447a444c64010492ff9f77e22bba46e6874"
        autoupdate.upstream = "https://github.com/Niek/chatgpt-web"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5174
